language: node_js

node_js:
  - "8"

branches:
  only:
  - master
  - develop
  - "/^v.*$/"

before_install:
  - gem install sass

before_script:
  - npm install

before_deploy:
  - npm run prerelease

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "vOqRJIRWTdZHAcO9B/8tBJOBgtFQimWrziDxvQPCepEVT6QADzk5hhbBlILtniYHD2IbgfsC40QLGKIFj5yQeIQm8LzbWTAEt/h2nn8NNEoaV5k2MICXafHwr8bZtG3Vublh+zaYFlNy1ZJNFr0nDFCdTdlFL2U7BkDSlKQlbrk/kOyWtRXufUzdCo/fOzZmLQReJpYNLdyRuEDkf/ClkADfsgvrp68RFRZ6QR5KnXj8Nf2lVfwGqhsTL6GFCItQVFPPhwTAHXiX7/xB/kbLyvpgqIGGeQV5Pm/AYepJEDsARChgaRzipQinHl90YBzrtq1LjlDEcT0bSHjLxc0rF2mPMNHXQpj9aq0IKfz/H1jB+7SO+NokjWjpi1Mk2O2IlEN0Ic185GEbIRi4FBpZUXU+41RtRX1t/HY2j/RmugLxmUO/UB3tX74dVtBfdpNkdZlef3TDrBeVHTOE8esG4OxhnRRTG6Eqkxps6jF4Najo9JVJBmNYQ4/+xK1zplzplZnyxn42wWAtTLTZv7x4kiEPlQb0UtL7CtnvpkPol36bK7Q957YV0lgo6ad1gEIcL8aj/Yf8DreWjApkEbnadV5a6+pv/FP6XaBl7FWUSMLlBcSbF+/7MXzT5sQznOPXQO5RPatjJBEmS3I2P6LUbV0QjoJLoBo2p6skRSR2mRs="
    file: "build.zip"
    on:
      branch: master
      tags: true
      repo: hms-dbmi/higlass-app
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: rk+Psp53H+dUqRjPG/3a08yLO9QOZvVd0GWXDx7TXIrbtHSFNZCi/+Tf0iOFTDnSuqq90shMYvC5gwj4exig/yVQ4p+KPDHrlUiwMWqNWuhXwXRxr3Gy+Xm+9/9HavdjFGgYQHASmu9gKKKaDqWTnZ5poFyz5WfHy3BRcJcg+bqBu2X+PcL5DKtBI4tp77cSHwXRZjR/4ddxKb05+xl0Z/xDxEaH53kAv9M15h97Lp1Tz0lddzgsramFIw61Mfdh6+BRCv+RzL8wrrYklAL77/upXKhtg6xJfLeArLibobYzPQYa9KWhobUFj7paxOxV+YpGu3eqRVTM5C+QBLNlnpBhOHxigUS9Tzeyw+igotHGXjVPgSA4ihCGqdVTUaHoLLWzgj4iddWQewzwFURfqNjoHduRBAxBN1yYz8GxQtcdiMuDRnP7O/kas9uVZurHztVGY7M7qU8ICgohllWOq9DAYgcpK6HRTS1QaCaPBNp9RNruyeMBSTQHBBsMjPCgtvRzgXoXcIrnV/Yh1PdSM1hj+RcI1TmZTjvX5KO1KH50l6O+8ipG+sHUHbTcuiOeA/YsFeuAISdf2wQUQd3szntcyfODw/XljGDS1TqnO0FgVgYY5UUeqPl0xTUweUtJmHNYZMJhAN6cqvdYc9ydmcibOPHYFPOSyzcZ7cr1Qg8=
    on:
      branch: master
      tags: true
      repo: hms-dbmi/higlass-app
